ServerName localhost
<Directory /var/www/konta>
    AllowOverride None
    Require all denied
</Directory>
<VirtualHost *:80>
    DocumentRoot /var/www/konta/webroot
    <Directory /var/www/konta/webroot>
        Options -Indexes +FollowSymLinks
        AllowOverride None
        Require all granted
        LimitRequestBody 12582912
        FallbackResource /index.php
    </Directory>
    Header always set X-Content-Type-Options "nosniff"
    ErrorLog /proc/self/fd/2
    CustomLog /proc/self/fd/1 combined
</VirtualHost>
