# Generated by Django 5.0.14 on 2026-08-31 13:18

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Bezeichnung",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="Notiz"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Erstellt am"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Geändert am"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="Gelöscht am"
                    ),
                ),
                (
                    "holder",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Inhaber"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("checking", "Girokonto"),
                            ("savings", "Sparkonto"),
                            ("credit", "Kreditkarte"),
                            ("cash", "Bargeld"),
                            ("investment", "Depot"),
                        ],
                        default="checking",
                        max_length=16,
                        verbose_name="Art",
                    ),
                ),
                (
                    "iban",
                    models.CharField(
                        blank=True, default="", max_length=34, verbose_name="IBAN"
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Bank"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="EUR", max_length=8, verbose_name="Währung"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, default="", max_length=32, verbose_name="Farbe"
                    ),
                ),
                (
                    "opening_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="Startsaldo",
                    ),
                ),
                (
                    "opening_balance_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Startsaldo am"
                    ),
                ),
                (
                    "include_in_net_worth",
                    models.BooleanField(default=True, verbose_name="Im Gesamtvermögen"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
            ],
            options={
                "verbose_name": "Konto",
                "verbose_name_plural": "Konten",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Bezeichnung",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="Notiz"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Erstellt am"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Geändert am"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="Gelöscht am"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=80, unique=True, verbose_name="Kürzel"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("income", "Einnahme"),
                            ("expense", "Ausgabe"),
                            ("both", "Beides"),
                        ],
                        default="expense",
                        max_length=16,
                        verbose_name="Art",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, default="", max_length=32, verbose_name="Farbe"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="Icon"
                    ),
                ),
                (
                    "keywords",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Hinweise für die automatische Zuordnung beim CSV-Import.",
                        verbose_name="Stichwörter",
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False, verbose_name="Standardkategorie"
                    ),
                ),
                (
                    "monthly_budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Monatsbudget",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kategorie",
                "verbose_name_plural": "Kategorien",
                "ordering": ("kind", "name"),
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Bezeichnung",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="Notiz"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Erstellt am"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Geändert am"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="Gelöscht am"
                    ),
                ),
                (
                    "interval",
                    models.CharField(
                        choices=[
                            ("weekly", "wöchentlich"),
                            ("biweekly", "zweiwöchentlich"),
                            ("monthly", "monatlich"),
                            ("quarterly", "vierteljährlich"),
                            ("semiannual", "halbjährlich"),
                            ("yearly", "jährlich"),
                            ("once", "einmalig"),
                        ],
                        default="monthly",
                        max_length=16,
                        verbose_name="Intervall",
                    ),
                ),
                (
                    "interval_count",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(60),
                        ],
                        verbose_name="Intervall-Faktor",
                    ),
                ),
                (
                    "day_of_month",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                        verbose_name="Tag im Monat",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Beginn")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="Ende"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "provider",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Anbieter"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="Betrag",
                    ),
                ),
                (
                    "contract_direction",
                    models.CharField(
                        choices=[("income", "Einnahme"), ("expense", "Ausgabe")],
                        default="expense",
                        max_length=16,
                        verbose_name="Richtung",
                    ),
                ),
                (
                    "contract_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="Vertragsnummer",
                    ),
                ),
                (
                    "cancellation_period_days",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Kündigungsfrist (Tage)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Vertrag",
                "verbose_name_plural": "Verträge",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Bezeichnung",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="Notiz"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Erstellt am"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Geändert am"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="Gelöscht am"
                    ),
                ),
                (
                    "interval",
                    models.CharField(
                        choices=[
                            ("weekly", "wöchentlich"),
                            ("biweekly", "zweiwöchentlich"),
                            ("monthly", "monatlich"),
                            ("quarterly", "vierteljährlich"),
                            ("semiannual", "halbjährlich"),
                            ("yearly", "jährlich"),
                            ("once", "einmalig"),
                        ],
                        default="monthly",
                        max_length=16,
                        verbose_name="Intervall",
                    ),
                ),
                (
                    "interval_count",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(60),
                        ],
                        verbose_name="Intervall-Faktor",
                    ),
                ),
                (
                    "day_of_month",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                        verbose_name="Tag im Monat",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Beginn")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="Ende"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "employer",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Arbeitgeber",
                    ),
                ),
                (
                    "gross_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="Brutto",
                    ),
                ),
                (
                    "net_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="Netto",
                    ),
                ),
                (
                    "tax_class",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=8,
                        verbose_name="Steuerklasse",
                    ),
                ),
                (
                    "part_time_factor",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("1.0000"),
                        help_text="1.0 = Vollzeit, 0.75 = 75 %.",
                        max_digits=5,
                        verbose_name="Teilzeitquote",
                    ),
                ),
            ],
            options={
                "verbose_name": "Einkommen",
                "verbose_name_plural": "Einkommen",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Bezeichnung",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="Notiz"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Erstellt am"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Geändert am"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="Gelöscht am"
                    ),
                ),
                (
                    "interval",
                    models.CharField(
                        choices=[
                            ("weekly", "wöchentlich"),
                            ("biweekly", "zweiwöchentlich"),
                            ("monthly", "monatlich"),
                            ("quarterly", "vierteljährlich"),
                            ("semiannual", "halbjährlich"),
                            ("yearly", "jährlich"),
                            ("once", "einmalig"),
                        ],
                        default="monthly",
                        max_length=16,
                        verbose_name="Intervall",
                    ),
                ),
                (
                    "interval_count",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(60),
                        ],
                        verbose_name="Intervall-Faktor",
                    ),
                ),
                (
                    "day_of_month",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                        verbose_name="Tag im Monat",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Beginn")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="Ende"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "lender",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Kreditgeber",
                    ),
                ),
                (
                    "principal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="Kreditsumme",
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.00"),
                        max_digits=6,
                        verbose_name="Zinssatz (% p. a.)",
                    ),
                ),
                (
                    "instalment",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="Rate",
                    ),
                ),
                (
                    "remaining_at_start",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Restschuld bei Beginn",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kredit",
                "verbose_name_plural": "Kredite",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Bezeichnung",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="Notiz"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Erstellt am"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Geändert am"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="Gelöscht am"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Positiv = Einnahme, negativ = Ausgabe.",
                        max_digits=14,
                        verbose_name="Betrag",
                    ),
                ),
                ("booking_date", models.DateField(db_index=True, verbose_name="Datum")),
                (
                    "state",
                    models.CharField(
                        choices=[("reality", "Gebucht"), ("planned", "Geplant")],
                        db_index=True,
                        default="planned",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manuell"),
                            ("import", "Import"),
                            ("generated", "Automatisch"),
                        ],
                        default="manual",
                        max_length=16,
                        verbose_name="Herkunft",
                    ),
                ),
                (
                    "counterparty",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Gegenseite",
                    ),
                ),
                (
                    "purpose",
                    models.TextField(
                        blank=True, default="", verbose_name="Verwendungszweck"
                    ),
                ),
                (
                    "recurrence_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=200,
                        verbose_name="Wiederholungsschlüssel",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Externe ID",
                    ),
                ),
                (
                    "import_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=64,
                        verbose_name="Import-Hash",
                    ),
                ),
                (
                    "classified_by_ai",
                    models.BooleanField(default=False, verbose_name="KI-Kategorie"),
                ),
                (
                    "classification_confidence",
                    models.FloatField(blank=True, null=True, verbose_name="Konfidenz"),
                ),
                (
                    "classification_note",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="Begründung",
                    ),
                ),
                (
                    "needs_review",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Prüfen"
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaktion",
                "verbose_name_plural": "Transaktionen",
                "ordering": ("-booking_date", "-created_at"),
            },
        ),
    ]
