# Generated by Django 5.0.14 on 2026-08-31 13:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Bezeichnung",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="Notiz"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Erstellt am"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Geändert am"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="Gelöscht am"
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="uploads/%Y/%m/", verbose_name="Datei"),
                ),
                (
                    "original_name",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Dateiname"
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        blank=True, default="", max_length=120, verbose_name="MIME-Typ"
                    ),
                ),
                ("size", models.BigIntegerField(default=0, verbose_name="Größe")),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("transaction_import", "Kontoumsätze (CSV)"),
                            ("document", "Dokument"),
                            ("other", "Sonstiges"),
                        ],
                        db_index=True,
                        default="document",
                        max_length=32,
                        verbose_name="Zweck",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Wartet"),
                            ("processing", "Wird verarbeitet"),
                            ("completed", "Abgeschlossen"),
                            ("failed", "Fehlgeschlagen"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                (
                    "stats",
                    models.JSONField(blank=True, default=dict, verbose_name="Ergebnis"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, default="", verbose_name="Fehler"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Verarbeitet am"
                    ),
                ),
            ],
            options={
                "verbose_name": "Datei",
                "verbose_name_plural": "Dateien",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Bezeichnung",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="Notiz"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Erstellt am"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Geändert am"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="Gelöscht am"
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        max_length=120,
                        unique=True,
                        verbose_name="Schlüssel",
                    ),
                ),
                (
                    "value",
                    models.JSONField(
                        blank=True, default=None, null=True, verbose_name="Wert"
                    ),
                ),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("string", "Text"),
                            ("number", "Zahl"),
                            ("boolean", "Ja/Nein"),
                            ("date", "Datum"),
                            ("json", "JSON"),
                        ],
                        default="string",
                        max_length=16,
                        verbose_name="Typ",
                    ),
                ),
                (
                    "is_secret",
                    models.BooleanField(default=False, verbose_name="Geheim"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Beschreibung"
                    ),
                ),
            ],
            options={
                "verbose_name": "Einstellung",
                "verbose_name_plural": "Einstellungen",
                "ordering": ("key",),
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Bezeichnung",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="Notiz"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Erstellt am"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Geändert am"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="Gelöscht am"
                    ),
                ),
                (
                    "db_table",
                    models.CharField(
                        db_index=True, max_length=120, verbose_name="Tabelle"
                    ),
                ),
                ("object_uuid", models.UUIDField(db_index=True, verbose_name="Objekt")),
                (
                    "color",
                    models.CharField(
                        blank=True, default="", max_length=32, verbose_name="Farbe"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "ordering": ("name",),
            },
        ),
    ]
