# Generated by Django 5.0.14 on 2026-08-31 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("base", "0001_initial"),
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="account",
            field=models.ForeignKey(
                blank=True,
                help_text="Konto, zu dem die importierten Umsätze gehören.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="files",
                to="finance.account",
                verbose_name="Konto",
            ),
        ),
    ]
